Library_Books_Check_in_out/code/librarian/config/routes.rb
Librarian::Application.routes.draw do |map|
  map.resources :books
  map.resources :menu
  map.resources :users
map.resources :book_check_out, :member => {:check_out => :put}
map.resources :book_check_in, :member => {:check_in => :put}
map.resources :book_search, :collection => {:search => :get}
map.resources :user_search, :collection => {:search => :get}

root :to => "menu#index"
map.connect ':controller/:action'
map.connect ':controller/:id/:action'
end

Library_Books_Check_in_out/code/librarian/app/models/user.rb
class User < ActiveRecord::Base
	has_and_belongs_to_many :books
	validates_presence_of :first_name
	validates_presence_of :last_name
	validates_uniqueness_of :last_name, :scope => :first_name, :message => "::Author with entered name already exists."
	validates_format_of :first_name, :with => /\A(^[a-zA-Z'.]{1,40})\Z/i
	validates_format_of :last_name, :with => /\A(^[a-zA-Z'.]{1,40})\Z/i

	def self.search(first_name, last_name)
    if first_name != nil and last_name != nil
      first_name_like = "%" + first_name + "%"
      last_name_like = "%" + last_name + "%"
      find(:all, :conditions => ['first_name LIKE ? AND last_name LIKE ?', first_name_like, last_name_like])
    end
  end

end

Library_Books_Check_in_out/code/librarian/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all
	@user = User.new
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
	params[:user][:first_name] = params[:user][:first_name].lstrip.rstrip.humanize
	params[:user][:last_name] = params[:user][:last_name].lstrip.rstrip.humanize
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.js
		format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.js { render :action => 'create_error' }
		format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
	params[:user][:first_name] = params[:user][:first_name].lstrip.rstrip.humanize
	params[:user][:last_name] = params[:user][:last_name].lstrip.rstrip.humanize
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    respond_to do |format|
     if @user.books.length == 0
      @user.destroy
        format.html { redirect_to(users_url, :notice => 'User was successfully deleted.')  }
		format.js
        format.xml  { head :ok }
      
     else
		@user.errors.add(:books, "This user has checked out one or more books and so cannot be deleted.")
		format.html { redirect_to(@user, :id => @user.id, :notice => 'This user has checked out one or more books and so cannot be deleted.') }
		format.js { render :action => 'delete_error'}
    end
   end
  end
end

Library_Books_Check_in_out/code/librarian/app/views/users/_edit_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, :placeholder => 'First Name' %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name, :placeholder => 'Last Name' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Library_Books_Check_in_out/code/librarian/app/views/users/_form.html.erb
<%= form_for(@user, :remote => true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div id="confirm">
</div>
<DIV id="error_details"></DIV>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, :placeholder => 'First Name' %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name, :placeholder => 'Last Name' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Library_Books_Check_in_out/code/librarian/app/views/users/_user.html.erb
<%= raw "<tr id='user_#{user.id}'>" %>
  <DIV id="error_details"></DIV>
  <td><%= user.first_name %>
  <%= user.last_name %></td>
  <td><%= link_to 'Show', user %></td>
  <td><%= link_to 'Edit', edit_user_path(user) %></td>
  <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete, :remote => true %></td>
</tr>

Library_Books_Check_in_out/code/librarian/app/views/users/_user_error.html.erb
<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

  <ul>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>

Library_Books_Check_in_out/code/librarian/app/views/users/edit.html.erb
<h1>Editing Member Details</h1>

<%= render 'edit_form' %>

<%= link_to (image_tag("/images/show.png")), @user %>
<%= link_to (image_tag("/images/home.png")), menu_index_path %>

Library_Books_Check_in_out/code/librarian/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Members</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
	<th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <%= render :partial => 'user', :locals => {:user => user }%>
<% end %>
</table>

<br />

<%= link_to (image_tag("/images/Add_User.png")), new_user_path %>
<%= link_to (image_tag("/images/Home.png")), menu_index_path %>

Library_Books_Check_in_out/code/librarian/app/views/users/new.html.erb
<h1>Add New Member</h1>

<%= render 'form' %>

<%= link_to (image_tag("/images/Home.png")), menu_index_path %>

Library_Books_Check_in_out/code/librarian/app/views/users/show.html.erb
<h1>Member Details</h1>

<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<% if @user.books.length > 0 %>
<p>
  <b>Books checked out:</b>
  <ul>
    <% for book in @user.books  %>
      <li>
        <%= book.title %> (<%= link_to 'Check In', book_check_in_path(book)%>)
      </li>
    <% end %>
  </ul>
</p>
<%else%>
  <p>No books checked out.</p>
<%end%>

<%= link_to (image_tag("/images/edit.png")), edit_user_path(@user) %>
<%= link_to (image_tag("/images/Home.png")), menu_index_path %>